// <auto-generated />
using System;
using BilsoftAnketPlatformu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilsoftAnketPlatformu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625224435_CorrectSurveyPersonnelAssignment")]
    partial class CorrectSurveyPersonnelAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.Anket", b =>
                {
                    b.Property<int>("AnketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("anketID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnketID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("aciklama");

                    b.Property<string>("AnketAdi")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("anket_adi");

                    b.HasKey("AnketID");

                    b.ToTable("anket", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.AnketCevap", b =>
                {
                    b.Property<int>("CevapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cevapID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CevapID"));

                    b.Property<int>("AnketID")
                        .HasColumnType("int")
                        .HasColumnName("anketID");

                    b.Property<string>("Cevap")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cevap");

                    b.Property<DateTime?>("KayitTarih")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("kayitTarih");

                    b.Property<int?>("PersonelID")
                        .HasColumnType("int")
                        .HasColumnName("personelID");

                    b.Property<int>("ServisNo")
                        .HasColumnType("int")
                        .HasColumnName("servisNo");

                    b.Property<int>("SoruID")
                        .HasColumnType("int")
                        .HasColumnName("soruID");

                    b.Property<int>("SoruTipi")
                        .HasColumnType("int")
                        .HasColumnName("soruTipi");

                    b.HasKey("CevapID");

                    b.ToTable("anket_cevaplar", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.AnketMusteri", b =>
                {
                    b.Property<bool>("AnketDurumu")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("anketDurumu");

                    b.Property<int>("AnketID")
                        .HasColumnType("int")
                        .HasColumnName("anketID");

                    b.Property<DateTime?>("AnketTarihKayit")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("anketTarihKayit");

                    b.Property<int?>("PersonelID")
                        .HasColumnType("int")
                        .HasColumnName("personelID");

                    b.Property<int>("ServisID")
                        .HasColumnType("int")
                        .HasColumnName("servisID");

                    b.ToTable("anket_musteri", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.AnketSoru", b =>
                {
                    b.Property<int>("SoruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("soruID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SoruID"));

                    b.Property<int>("AnketID")
                        .HasColumnType("int")
                        .HasColumnName("anketID");

                    b.Property<int?>("SiraNo")
                        .HasColumnType("int")
                        .HasColumnName("siraNo");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("soru");

                    b.Property<int>("SoruTipi")
                        .HasColumnType("int")
                        .HasColumnName("soruTipi");

                    b.HasKey("SoruID");

                    b.ToTable("anket_sorular", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            ConcurrencyStamp = "admin-role-stamp",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "kullanici-role-id",
                            ConcurrencyStamp = "kullanici-role-stamp",
                            Name = "Kullanici",
                            NormalizedName = "KULLANICI"
                        });
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("longtext");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            AdSoyad = "Sistem Admin",
                            AktifMi = true,
                            ConcurrencyStamp = "admin-concurrency-stamp",
                            Email = "admin@bilsoft.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BILSOFT.COM",
                            NormalizedUserName = "ADMIN@BILSOFT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMygiBagleiMV23HKs8YExyJ/zKlwTYtbsWe+fn1f2psIg5fBcuXIBFepu+XT3Qq0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "admin@bilsoft.com"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            AdSoyad = "Ayse Kullanici",
                            AktifMi = true,
                            ConcurrencyStamp = "ayse-concurrency-stamp",
                            Email = "ayse@bilsoft.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AYSE@BILSOFT.COM",
                            NormalizedUserName = "AYSE@BILSOFT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDaj7mispSCG7o7/wiv8A2QH+/tXM44u4hEAqnCQl4r1zyYUNnVtqw2vUW3/cDWALQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ayse-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "ayse@bilsoft.com"
                        });
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.AppUserPersonel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelID");

                    b.HasIndex("UserId", "PersonelID")
                        .IsUnique();

                    b.ToTable("AppUserPersonel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonelID = 2,
                            UserId = "22222222-2222-2222-2222-222222222222"
                        });
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PersonelID");

                    b.ToTable("Personel", (string)null);

                    b.HasData(
                        new
                        {
                            PersonelID = 1,
                            AdSoyad = "Ahmet Yilmaz",
                            AktifMi = true
                        },
                        new
                        {
                            PersonelID = 2,
                            AdSoyad = "Ayse Demir",
                            AktifMi = true
                        },
                        new
                        {
                            PersonelID = 3,
                            AdSoyad = "Mehmet Kaya",
                            AktifMi = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111111",
                            RoleId = "admin-role-id"
                        },
                        new
                        {
                            UserId = "22222222-2222-2222-2222-222222222222",
                            RoleId = "kullanici-role-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.AppUserPersonel", b =>
                {
                    b.HasOne("BilsoftAnketPlatformu.Models.Personel", "Personel")
                        .WithMany("AppUserPersoneller")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilsoftAnketPlatformu.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BilsoftAnketPlatformu.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BilsoftAnketPlatformu.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BilsoftAnketPlatformu.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BilsoftAnketPlatformu.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilsoftAnketPlatformu.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BilsoftAnketPlatformu.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BilsoftAnketPlatformu.Models.Personel", b =>
                {
                    b.Navigation("AppUserPersoneller");
                });
#pragma warning restore 612, 618
        }
    }
}
